BaseURL = "https://foreversmart.cc/"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "Foreversmart"
Theme = "hugo-sirity-theme"
pygmentsStyle = "default"
pygmentsUseClasses = true
paginate = 3

[Author]
  Name = "coderzh"

[outputs]
  home = [ "RSS", "HTML" ]
    
[outputFormats] 
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[Params]
  AuthorHomepage = "https://foreversmart.cc/"
  BottomIntroduce = "分享交流和传递"
  Description = ""
  Subtitle = "永恒空间"
  Weibo = "foreversmart"
  WeiboID = "foreversmart"
  Twitter = "njutree"
  GitHub = "foreversmart"
  Imglogo = "img/logo.jpg"
  AuthorImg = "img/author.jpg"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true

  [Params.GoogleAnalytics]
    ID = "UA-10147768-2"

  [Params.Disqus]
    ShortName = "foreversmart"

  [Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

[Menu]
  [[Menu.Main]]
    Name = "首页"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 2